# Generated by Django 4.2.6 on 2023-10-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_task_created_at_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
